{% set name = "ttfunk" %}
{% set version = "1.8.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: a7cbc7e489cc46e979dde04d34b5b9e4f5c8f1ee5fc6b1a7be39b829919d20ca

build:
  noarch: generic
  number: 1
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-bigdecimal ~=3.1

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://prawnpdf.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - GPLv2
    - GPLv3
  summary: |
    Font Metrics Parser for the Prawn PDF generator
  description:
  doc_url: https://prawnpdf.org/docs/ttfunk/
  dev_url: https://github.com/prawnpdf/ttfunk
extra:
  recipe-maintainers:
    - jdmarques
